In [23]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate error
error = (output - target)

# TODO: Calculate error gradient for output layer
del_err_output = error*(hidden_layer_output)*(1 - hidden_layer_output)

# TODO: Calculate error gradient for hidden layer
del_err_hidden = del_err_output*weights_hidden_output*(hidden_layer_output)*(1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate*del_err_output*weights_hidden_output*hidden_layer_output

print(del_err_hidden)
print(weights_input_hidden)
print(np.dot(del_err_hidden, weights_input_hidden.T))

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate*np.dot(del_err_hidden, weights_input_hidden.T)*x

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)


[ 0.00018068 -0.00052179]
[[ 0.5 -0.6]
 [ 0.1 -0.2]
 [ 0.1  0.7]]
[ 0.00040341  0.00012243 -0.00034718]
Change in weights for hidden layer to output layer:
[ 0.00020518 -0.00042559]
Change in weights for input layer to hidden layer:
[  1.00852730e-04   6.12125332e-06   3.47182359e-05]
