In [18]:
import re
import random
import numpy as np
import os.path
import scipy.misc
import shutil
import zipfile
import time
import tensorflow as tf
from glob import glob
from urllib.request import urlretrieve
from tqdm import tqdm

In [16]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf

#tf.enable_eager_execution()

In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))  # => "hello, [[4.]]"

hello, [[4.]]


In [7]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

# Broadcasting support
b = tf.add(a, 1)
print(b)

# Operator overloading is supported
print(a * b)

# Use NumPy values
import numpy as np

c = np.multiply(a, b)
print(c)

# Obtain numpy value from a tensor:
print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)
[[ 2  6]
 [12 20]]
[[1 2]
 [3 4]]


In [15]:
y = tf.matmul([[37.0, -23.0], [1.0, 4.0]], tf.random_uniform([2, 2]))

with tf.Session() as sess:
  # Define options for the `sess.run()` call.
  options = tf.RunOptions()
  options.output_partition_graphs = True
  options.trace_level = tf.RunOptions.FULL_TRACE

  sess.run(y)

#   # Define a yontainer for the returned metadata.
#   metadata = tf.RunMetadata()

#   sess.run(y, options=options, run_metadata=metadata)

#   # Print the subgraphs that executed on each device.
#   print(metadata.partition_graphs)

#   # Print the timings of each operation that executed.
#   print(metadata.step_stats)


RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [22]:
data_folder = './data/data_road/training'

image_paths = glob(os.path.join(data_folder, 'image_2', '*.png'))
label_paths = {
    re.sub(r'_(lane|road)_', '_', os.path.basename(path)): path
    for path in glob(os.path.join(data_folder, 'gt_image_2', '*_road_*.png'))}
print(label_paths)

{'um_000087.png': './data/data_road/training/gt_image_2/um_road_000087.png', 'um_000093.png': './data/data_road/training/gt_image_2/um_road_000093.png', 'um_000044.png': './data/data_road/training/gt_image_2/um_road_000044.png', 'um_000050.png': './data/data_road/training/gt_image_2/um_road_000050.png', 'um_000078.png': './data/data_road/training/gt_image_2/um_road_000078.png', 'uu_000073.png': './data/data_road/training/gt_image_2/uu_road_000073.png', 'uu_000067.png': './data/data_road/training/gt_image_2/uu_road_000067.png', 'umm_000007.png': './data/data_road/training/gt_image_2/umm_road_000007.png', 'umm_000013.png': './data/data_road/training/gt_image_2/umm_road_000013.png', 'umm_000012.png': './data/data_road/training/gt_image_2/umm_road_000012.png', 'umm_000006.png': './data/data_road/training/gt_image_2/umm_road_000006.png', 'uu_000066.png': './data/data_road/training/gt_image_2/uu_road_000066.png', 'uu_000072.png': './data/data_road/training/gt_image_2/uu_road_000072.png', 'um